from enum import StrEnum


class ApcName(StrEnum):
    NAMWON = "NAMWON"
    WIMI = "WIMI"
    SEOGWI = "SEOGWI"
    JUNGMUN = "JUNGMUN"
    GUJWA = "GUJWA"


class CropType(StrEnum):
    CITRUS = "CITRUS"
    CARROT = "CARROT"


class SnpSe(StrEnum):
    WRHS = "WRHS"
    CLSFY = "CLSFY"


class MonitoringStatus(StrEnum):
    NORMAL = "NORMAL"
    DELAYED = "DELAYED"
    ERROR = "ERROR"
    MISSING = "MISSING"
    UNDEFINED_RULE = "UNDEFINED_RULE"


class IssueStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class IssueSeverity(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class PipelineStepStatus(StrEnum):
    SUCCESS = "SUCCESS"
    RUNNING = "RUNNING"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    UNDEFINED = "UNDEFINED"


class PipelineStepKey(StrEnum):
    API_RECEIVED = "API_RECEIVED"
    AUTH_SCHEMA_VALIDATED = "AUTH_SCHEMA_VALIDATED"
    ORIGIN_SAVED = "ORIGIN_SAVED"
    REFINED_SAVED = "REFINED_SAVED"
    AIRFLOW_SNAPSHOT_LOADED = "AIRFLOW_SNAPSHOT_LOADED"
    GUIDANCE_API_AVAILABLE = "GUIDANCE_API_AVAILABLE"
    SCREEN_RENDERED = "SCREEN_RENDERED"


class IssueType(StrEnum):
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"
    INVALID_FORMAT = "INVALID_FORMAT"
    DUPLICATE_SUSPECTED = "DUPLICATE_SUSPECTED"
    OUTLIER_QUANTITY_WEIGHT = "OUTLIER_QUANTITY_WEIGHT"
    UNSUPPORTED_APC_CROP = "UNSUPPORTED_APC_CROP"
    REFINED_FAILED = "REFINED_FAILED"


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"
