"""Framework-independent domain contracts."""

from app.domain.document import (
    DiagnosticSeverity,
    DocumentConflict,
    DocumentDetail,
    DocumentDiagnostic,
    DocumentDraft,
    DocumentFormat,
    DocumentPosition,
    DocumentSummary,
)
from app.domain.errors import DomainError
from app.domain.project import Project, ProjectHealth
from app.domain.review_workflow import (
    Actor,
    ActorRole,
    AuditRecord,
    ChangeStatus,
    ChangeWorkflow,
    ContextVersionRecord,
    EvidenceRecord,
    EvidenceResult,
    EvidenceType,
    GateBlocker,
    GitPublication,
    QaScenario,
    ReviewDecision,
    ReviewRecord,
    SemanticDiff,
    activate_context,
    current_evidence,
    demo_workflow,
    record_evidence,
    record_git_publication,
    record_review,
    review_denial,
    transition_workflow,
    validate_git_publication,
    verification_gate,
)
from app.domain.security import AuthenticatedPrincipal, AuthSession, OidcFlow

__all__ = [
    "Actor",
    "ActorRole",
    "AuditRecord",
    "AuthSession",
    "AuthenticatedPrincipal",
    "ChangeStatus",
    "ChangeWorkflow",
    "ContextVersionRecord",
    "DiagnosticSeverity",
    "DocumentConflict",
    "DocumentDetail",
    "DocumentDiagnostic",
    "DocumentDraft",
    "DocumentFormat",
    "DocumentPosition",
    "DocumentSummary",
    "DomainError",
    "EvidenceRecord",
    "EvidenceResult",
    "EvidenceType",
    "GateBlocker",
    "GitPublication",
    "OidcFlow",
    "Project",
    "ProjectHealth",
    "QaScenario",
    "ReviewDecision",
    "ReviewRecord",
    "SemanticDiff",
    "activate_context",
    "current_evidence",
    "demo_workflow",
    "record_evidence",
    "record_git_publication",
    "record_review",
    "review_denial",
    "transition_workflow",
    "validate_git_publication",
    "verification_gate",
]
